=== veltzer/java-keynote/xsd/keynote.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://veltzer.org/keynote"
	xmlns:tns="https://veltzer.org/keynote"
	elementFormDefault="qualified">

	<xsd:element name="presentation" type="tns:Presentation">
		<xsd:annotation>
			<xsd:documentation>
				This is the presentation element
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="Slide">
		<xsd:sequence>
			<xsd:element name="title" maxOccurs="1" minOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="bullet" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType mixed="true">
					<xsd:sequence>
						<xsd:element name="email" type="xsd:string" minOccurs="0" maxOccurs="unbounded">
						</xsd:element>
						<xsd:element name="code" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType mixed="true">
								<xsd:sequence></xsd:sequence>
								<xsd:attribute name="language" type="xsd:string"></xsd:attribute>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="concept" type="xsd:string" minOccurs="0" maxOccurs="unbounded">
						</xsd:element>
						<xsd:element name="emphasis" type="xsd:string" minOccurs="0" maxOccurs="unbounded">
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="size" type="xsd:string"></xsd:attribute>
					<xsd:attribute name="align" type="xsd:string"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="template" type="xsd:string">
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="Keywords">
		<xsd:sequence>
			<xsd:element name="keyword" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						This is a single keyword
					</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Author">
		<xsd:sequence>
			<xsd:element name="firstname">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="surname">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Meta">
		<xsd:annotation>
			<xsd:documentation>
				This is the meta element
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="title" maxOccurs="1" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="author" type="tns:Author" maxOccurs="1" minOccurs="0"></xsd:element>	
			<xsd:element name="copyright" maxOccurs="1" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string"></xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="keywords" type="tns:Keywords" maxOccurs="1" minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Presentation">
		<xsd:annotation>
			<xsd:documentation>
			This is a full keynote presentation
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="meta" type="tns:Meta" maxOccurs="1"/>
			<xsd:element name="slide" type="tns:Slide" maxOccurs="unbounded"/>
  		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== veltzer/java-keynote/presentations/unicode.xml
<?xml version="1.0" encoding="UTF-8"?>
<presentation
	xmlns="https://veltzer.org/keynote"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://veltzer.org/keynote https://veltzer.org/keynote/xsd/keynote.xsd"
	>
	<meta>
		<title>Unicode test</title>
		<author>
			<firstname value="מרק"/>
			<surname value="ולצר"/>
		</author>
		<copyright>this is the copyright</copyright>
		<keywords>
			<keyword value="אחד"/>
			<keyword value="שנים"/>
			<keyword value="שלוש"/>
		</keywords>
	</meta>
	<slide template="bullet">
		<title>?כותרת ללא צידוד</title>
		<bullet align="center">אלמנט ממורכז</bullet>
		<bullet align="left">אלמנט מצודד לימין</bullet>
		<bullet align="right">אלמנט מצודד לשמאל</bullet>
		<bullet align="right">יאת כתיב נאה</bullet>
		<bullet align="right">right bullet</bullet>
		<bullet align="left">left bullet</bullet>
		<bullet align="center">center bullet</bullet>
	</slide>
	<slide template="bullet">
		<title>some English too?</title>
		<bullet>must have one bullet, at least</bullet>
		<bullet>misspell</bullet>
	</slide>
</presentation>

=== veltzer/java-keynote/presentations/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This presentation is here for me to test various features of keynote. 
	Mark Veltzer, 2011 -->
<presentation
	xmlns="https://veltzer.org/keynote"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://veltzer.org/keynote https://veltzer.org/keynote/xsd/keynote.xsd">
	<meta>
		<title>
			This is the title
		</title>
		<author>
			<firstname value="Mark" />
			<surname value="Veltzer" />
		</author>
		<copyright>this is the copyright</copyright>
		<keywords>
			<keyword value="one" />
			<keyword value="two" />
			<keyword value="three" />
		</keywords>
	</meta>
	<slide template="center">
		<title>This is the title</title>
		<bullet align="center">The present slide making software</bullet>
		<bullet align="center">
			Mark Veltzer
			<email>mark.veltzer@gmail.com</email>
		</bullet>
	</slide>
	<slide template="flowing">
		<title>What is keynote ?</title>
		<bullet>
			<concept>Present</concept>
			is tool to create presentations from text files.
		</bullet>
		<bullet>The idea is to be able to edit presentations with a regular
			text editor.
		</bullet>
	</slide>
	<slide template="flowing">
		<title>Why should I use keynote ?</title>
		<bullet>You want to keep the source of your presentation in source
			control.</bullet>
		<bullet>You hate using a WYSIWYG editor.</bullet>
		<bullet>It allows many people to work on the same presentation at the
			same time and resolve their differences using common tools.
		</bullet>
		<bullet>
			<code>This is some C code</code>
		</bullet>
		<bullet>It separates content and presentation.
		</bullet>
		<bullet>It forces same look and feel on all of your presentations.
		</bullet>
		<bullet>Presentations look better because they are generated by
			machine and all the text is well aligned.
		</bullet>
		<bullet>You can convert the content to many types: PDF, ODP, HTML and
			more.
		</bullet>
	</slide>
</presentation>

=== veltzer/java-keynote/presentations/keynote.xml
<?xml version="1.0" encoding="UTF-8"?>
<presentation
	xmlns="https://veltzer.org/keynote"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://veltzer.org/keynote https://veltzer.org/keynote/xsd/keynote.xsd"
	>
	<meta>
		<title>The keynote slide manager</title>
		<author>
			<firstname value="Mark"/>
			<surname value="Veltzer"/>
		</author>
		<copyright>Copyright (c) 2011, 2012 Mark Veltzer</copyright>
		<keywords>
			<keyword value="keynote"/>
			<keyword value="Mark Veltzer"/>
			<keyword value="presentations"/>
			<keyword value="power point"/>
		</keywords>
	</meta>
	<slide template="center">
		<title>This is the first title</title>
		<bullet><concept>Keynote</concept></bullet>
		<bullet>slides made right</bullet>
		<!-- <vspace/> -->
		<bullet size="small">Mark Veltzer</bullet>
		<bullet size="small"><email>mark.veltzer@gmail.com</email></bullet>
	</slide>
	<slide template="flowing">
		<title>This is the title</title>
		<bullet>1. this is a slide</bullet>
		<bullet>2. with just bullets</bullet>
		<bullet>3. each bullet should fit</bullet>
		<bullet>4. into one line</bullet>
		<bullet>5. you should see exactly</bullet>
		<bullet>6. the number of lines</bullet>
		<bullet>7. you configured to see in each</bullet>
		<bullet>8. slide</bullet>
	</slide>
	<slide template="flowing">
		<title>Slide created without a layout manager</title>
		<bullet>This means that this slide will have a flow layout manager</bullet>
		<bullet>And this is yet another bullet</bullet>
	</slide>
	<slide template="flowing">
		<title>Long Slide</title>
		<bullet>This slide</bullet>
		<bullet>has many</bullet>
		<bullet>many</bullet>
		<bullet>and many</bullet>
		<bullet>very</bullet>
		<bullet>many</bullet>
		<bullet>very</bullet>
		<bullet>many</bullet>
		<bullet>bullets</bullet>
		<bullet>They are intended to make the flow layout break it into a couple of slides</bullet>
	</slide>
	<slide template="flowing">
		<title>What is keynote?</title>
		<bullet><emphasis>Keynote</emphasis> is tool to create presentations from text files.</bullet>
		<bullet>The idea is to be able to edit presentations with a regular text editor.</bullet>
	</slide>
	<slide template="flowing">
		<title>This is a code slide</title>
		<bullet>This is a sample of code:</bullet>
		<bullet>
			<code language="c"><![CDATA[
			int main(int argc,char** argv, char** envp) {
				printf("Hello, World!\n");
				return 0;
			}
			]]></code>
		</bullet>
		<bullet>And this is a discussion of it</bullet>
	</slide>
	<slide template="flowing">
		<title>Features</title>
		<bullet>Syntax highlighting for pieces of code.</bullet>
		<bullet>Presentations can be viewed over the web using a regular browser with no plugins.</bullet>
		<bullet>Presentations are a lot sexier than PDF or PowerPoint</bullet>
		<bullet>Presentations are simple to create, no need for big software</bullet>
		<bullet>Presentations look good on any screen size because of layout manager used within keynote</bullet>
		<bullet>Presentations stay small in size</bullet>
	</slide>
	<slide template="flowing">
		<title>Why should I use keynote ?</title>
		<bullet>You want to keep the source of your presentation in source control.</bullet>
		<bullet>You hate using a <concept>WYSIWYG</concept> editor.</bullet>
		<bullet>It allows many people to work on the same presentation at the same time and resolve their differences using common tools.</bullet>
		<bullet>It separates content and presentation.</bullet>
		<bullet>It forces same look and feel on all of your presentations.</bullet>
		<bullet>Presentations look better because they are generated by machine and all the text is well aligned.</bullet>
		<bullet>You can convert the content to many types: PDF, ODP, HTML and more.</bullet>
	</slide>
	<slide template="flowing">
		<title>Writing presentations in keynote</title>
		<bullet>You can use any editor you like (I use vim)</bullet>
		<bullet>An empty presentation would look like this:</bullet>
		<bullet>
			<code language="xml"><![CDATA[
			<?xml version="1.0" encoding="ISO-8859-1"?>
			<presentation
				xmlns:xsi="https://veltzer.org/keynote/"
				xsi:noNamespaceSchemaLocation="keynote.xsd">
			</presentation>
			]]></code>
		</bullet>
	</slide>
	<slide template="flowing">
		<title>Comparison to other solutions</title>
		<bullet>DocBook is nice but not tuned to slides.</bullet>
		<!-- todo: talk about openoffice, pdf, other tools -->
	</slide>
	<slide template="flowing">
		<title>Browser support</title>
		<bullet>keynote is developed on a recent version of chrome and that is the browser that it supports the best</bullet>
		<bullet>Latest versions of chrome and Firefox are supported.</bullet>
		<bullet>Other browsers will be supported only if users report and help out with bugs.</bullet>
		<bullet>Keynote does use jQuery at the bottom layer and browser independent
		coding and so it is quite portable and bug fixes should not be hard</bullet>
		<bullet>Browser support is an issue which is not of equal importance to all users</bullet>
		<!--
		<subbullet>presenters don't mind installing a browser that works</subbullet>
		<subbullet>websites want keynote to work on all browsers</subbullet>
		-->
		<bullet>This means that if you are a person doing presentations you have more incentive to work
		with keynote even before it reaches maturity with all browsers</bullet>
	</slide>
	<slide template="flowing">
		<title>Keynote philosophy</title>
		<bullet>Content should always be in text files.</bullet>
		<bullet>Customization of graphics and look and feel are not very important.</bullet>
		<bullet>Separation of content and presentation is important.</bullet>
		<bullet>Simplicity in UI is a good thing.</bullet>
		<bullet>Big software is evil. Lots of small pieces of software is good.</bullet>
		<bullet>Mark is always right, especially when he is dead wrong.</bullet>
	</slide>
</presentation>

=== veltzer/java-keynote/presentations/jquery.xml
<?xml version="1.0" encoding="UTF-8"?>

<presentation
	xmlns="https://veltzer.org/keynote"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://veltzer.org/keynote file://keynote.xsd"
	>
	<!-- 
	xsi:schemaLocation="https://veltzer.org/keynote https://veltzer.org/keynote/xsd/keynote.xsd
	 -->
	<meta>
		<title>jQuery</title>
		<author>
			<firstname value="Mark"/>
			<surname value="Veltzer"/>
		</author>
		<copyright>Copyright (c) 2011, 2012 Mark Veltzer</copyright>
		<keywords>
			<keyword value="jQuery"/>
			<keyword value="Mark Veltzer"/>
			<keyword value="introduction"/>
			<keyword value="tutorial"/>
			<keyword value="presentation"/>
			<keyword value="keynotejs"/>
		</keywords>
	</meta>
	<slide template="center">
		<title>jQuery</title>
		<bullet>Mark Veltzer</bullet>
		<bullet><email>mark.veltzer@gmail.com</email></bullet>
		<!--image url='jquery.png' description='the jQuery logo'/-->
	</slide>
	<slide template="flow">
		<title>Second jQuery slide</title>
		<bullet>this is a bullet</bullet>
	</slide>
</presentation>

=== veltzer/java-keynote/presentations/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<presentation
	xmlns="https://veltzer.org/keynote"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://veltzer.org/keynote https://veltzer.org/keynote/xsd/keynote.xsd"
	>
	<meta>
		<title>This is the title</title>
	</meta>
	<slide template="centered">
		<title>This is the first slide</title>
		<bullet>Mark Veltzer</bullet>
		<bullet><email>mark.veltzer@gmail.com</email></bullet>
	</slide>
	<slide template="bullets">
		<title>This is slide 2</title>
		<bullet>This is the first bullet</bullet>
		<bullet>This is the second bullet</bullet>
	</slide>
</presentation>
